filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

logging.level: error

filebeat.inputs:
  - type: stdin


output.kafka:
  # initial brokers for reading cluster metadata
  hosts: ["10.2.20.101:9092", "10.2.20.102:9092", "10.2.20.103:9092"]

  # message topic selection + partitioning
  topic: 'logs'
  partition.round_robin:
    reachable_only: false

  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
